class_name Quotes
extends RefCounted
## Реплики бойцов: перед боем (экран «ПРОТИВ») и после победы в матче.
## Тон — «пафос + юмор». Каждая реплика — [русский, английский]. Истории и смысл пар — docs/LORE.md.
## Вариант выбирается по зерну матча; у каждого героя по 3 общие реплики до и после боя,
## у каждой встречи — свои диалоги (у разных героев — по 2, у пар-соперников — больше).

## Перед боем: пара бойцов (по алфавиту) → варианты диалога; в диалоге — [кто говорит, ru, en].
const INTRO := {
	"anubis|athena": [
		[["anubis", "Богиня справедливости и бог суда. Нам есть о чём поговорить.",
			"The goddess of justice and the god of judgement. We have much to discuss."],
		["athena", "После боя. Справедливость любит тишину.",
			"After the fight. Justice likes silence."]],
		[["athena", "Ты взвешиваешь сердца. Моё тоже взвесишь?",
			"You weigh hearts. Will you weigh mine?"],
		["anubis", "Оно тяжелее, чем ты думаешь. Медуза знает почему.",
			"It is heavier than you think. Medusa knows why."]],
	],
	"anubis|dracula": [
		[["anubis", "Ты должен был прийти ко мне пятьсот лет назад, князь.",
			"You were due to come to me five hundred years ago, prince."],
		["dracula", "Я опаздываю. Это аристократично.",
			"I am running late. It is aristocratic."]],
		[["dracula", "Страж мёртвых с головой шакала. Мы с вами почти коллеги.",
			"A jackal-headed guardian of the dead. We are almost colleagues."],
		["anubis", "Нет. Я провожаю мёртвых. Ты их создаёшь.",
			"No. I guide the dead. You make them."]],
	],
	"anubis|hercules": [
		[["anubis", "Ты спускался в царство мёртвых и увёл оттуда пса. Мой коллега обиделся.",
			"You went down to the underworld and took its dog. My colleague was offended."],
		["hercules", "Цербер сам за мной пошёл! Хочешь, и тебя выгуляю?",
			"Cerberus followed me on his own! Want me to walk you too?"]],
		[["hercules", "Бог с головой шакала? Видал я зверей и пострашнее.",
			"A god with a jackal's head? I've seen scarier beasts."],
		["anubis", "Видал. Но взвешивать тебя будут не они.",
			"You have. But they are not the ones who will weigh you."]],
	],
	"anubis|ilya": [
		[["anubis", "Илья Муромец. Твоё сердце тяжело от подвигов. Посмотрим, что перевесит.",
			"Ilya Muromets. Your heart is heavy with deeds. Let us see what outweighs."],
		["ilya", "Сердце моё не трожь, пёсья голова. Оно на Русь заведено.",
			"Keep your paws off my heart, dog-head. It beats for Rus."]],
		[["ilya", "Это что ж за зверь — человек с собачьей головой?",
			"What kind of beast is this — a man with a dog's head?"],
		["anubis", "Тот, кто однажды взвесит и тебя. Не торопись ко мне, богатырь.",
			"The one who will weigh you one day. Do not hurry to me, hero."]],
	],
	"anubis|koschei": [
		[["anubis", "Твоё имя есть в моих списках. Твоей смерти — нет.",
			"Your name is on my lists. Your death is not."],
		["koschei", "Найдёшь иглу — забирай. Я, может, даже рад буду.",
			"Find the needle and it's yours. I might even be glad."]],
		[["koschei", "Пёс мёртвых. Пришёл за мной? Ну наконец-то.",
			"Hound of the dead. Come for me? At last."],
		["anubis", "Не сегодня. Сегодня — только бой.",
			"Not today. Today there is only the fight."]],
	],
	"anubis|medusa": [
		[["anubis", "Сколько душ ты обратила в камень, Горгона? Я веду им счёт.",
			"How many souls have you turned to stone, Gorgon? I keep count."],
		["medusa", "Все они пришли за моей головой. Взвесь и это.",
			"Every one of them came for my head. Weigh that too."]],
		[["medusa", "Шакал. Ты тоже пришёл меня судить?",
			"Jackal. Have you come to judge me too?"],
		["anubis", "Нет. Судят весы. Я лишь держу их ровно.",
			"No. The scales judge. I only hold them level."]],
	],
	"anubis|sunwukong": [
		[["anubis", "Сунь Укун. Твоё имя вычеркнуто из Книги жизни и смерти. Весы не терпят пустых строк.",
			"Sun Wukong. Your name is struck from the Book of Life and Death. The scales cannot abide an empty line."],
		["sunwukong", "Вычеркнуто — значит, меня нет! Кого ты тогда ловишь, пёсик?",
			"Struck out — so I don't exist! Then who are you chasing, doggy?"]],
		[["sunwukong", "Эй, шакал! Догонишь — отдам посох. Не догонишь — отдашь весы!",
			"Hey, jackal! Catch me and the staff is yours. Don't — and I get your scales!"],
		["anubis", "Все бегут от смерти. Ни один ещё не добежал.",
			"Everyone runs from death. No one has ever made it."]],
	],
	"athena|dracula": [
		[["dracula", "Богиня мудрости! Как мило. Не желаете поужинать со мной?",
			"The goddess of wisdom! How charming. Would you care to dine with me?"],
		["athena", "Мудрость — это отказаться от приглашения вампира.",
			"Wisdom is declining a vampire's invitation."]],
		[["athena", "Ты стратег, граф. Я читала о твоих войнах.",
			"You are a strategist, Count. I have read of your wars."],
		["dracula", "Как лестно. Обычно обо мне читают совсем другое.",
			"How flattering. People usually read something else about me."]],
	],
	"athena|hercules": [
		[["athena", "Геракл. Я помогала тебе во всех подвигах. Помнишь?",
			"Hercules. I helped you through every labour. Remember?"],
		["hercules", "Помню, сестрица! Потому и бить буду вполсилы. Шучу!",
			"I remember, sister! So I'll only hit at half strength. Kidding!"]],
		[["hercules", "Афина! Разомнёмся, как в старые добрые?",
			"Athena! A warm-up, like the good old days?"],
		["athena", "Как в старые добрые: ты бьёшь, я думаю. Защищайся.",
			"Like the old days: you swing, I think. Defend yourself."]],
	],
	"athena|ilya": [
		[["athena", "Ты силён, богатырь. Но сила без стратегии — просто шум.",
			"You are strong, hero. But strength without strategy is just noise."],
		["ilya", "Стратегия у меня одна, матушка: палицей — и в поле.",
			"I've got one strategy, ma'am: the mace, and out into the field."]],
		[["ilya", "Девица с копьём? У нас таких поляницами зовут. Уважаю.",
			"A maiden with a spear? Back home we call them polyanitsy. Respect."],
		["athena", "Богиня, а не девица. Но уважение принимаю. Защищайся.",
			"A goddess, not a maiden. But I accept the respect. Defend yourself."]],
	],
	"athena|koschei": [
		[["athena", "Кощей. Ты спрятал смерть, чтобы не платить по счетам.",
			"Koschei. You hid your death so you'd never pay your debts."],
		["koschei", "А ты наказала невиновную — и тоже не заплатила. Квиты, богиня.",
			"And you punished an innocent — and never paid either. We're even, goddess."]],
		[["koschei", "Мудрая, скажи: зачем жить вечно, если ничего не чувствуешь?",
			"Tell me, wise one: why live forever if you feel nothing?"],
		["athena", "Не знаю. Но бой — хороший способ проверить.",
			"I don't know. But a fight is a good way to find out."]],
	],
	"athena|medusa": [
		[["athena", "Медуза. Ты обращаешь в камень всех, кто приходит. Этому пора положить конец.",
			"Medusa. You turn to stone everyone who comes. This has to end."],
		["medusa", "Конец положила ты — в своём храме. Меня обидели, а наказала ты — меня. Посмотри мне в глаза, богиня.",
			"You put an end to me — in your own temple. I was wronged, and you punished me. Look me in the eye, goddess."]],
		[["medusa", "Пришла за моей головой, как все твои «герои»?",
			"Come for my head, like all your «heroes»?"],
		["athena", "Я пришла… за ответом. Сначала — поединок. Потом — правда.",
			"I came… for an answer. First the duel. Then the truth."]],
	],
	"athena|sunwukong": [
		[["sunwukong", "Богиня мудрости! Загадай загадку — а я отвечу посохом!",
			"Goddess of wisdom! Ask me a riddle — I'll answer with my staff!"],
		["athena", "Загадка: что быстрее обезьяны? Ответ: копьё.",
			"Riddle: what is faster than a monkey? Answer: a spear."]],
		[["athena", "Хаос на ножках. Это ты разгромил небесный дворец?",
			"Chaos on legs. Was it you who wrecked the heavenly palace?"],
		["sunwukong", "Только чуть-чуть! И персики съел. Все.",
			"Only a little! And ate the peaches. All of them."]],
	],
	"dracula|hercules": [
		[["hercules", "Вампир! Будешь моим тринадцатым подвигом — коротким!",
			"A vampire! You'll be my thirteenth labour — a short one!"],
		["dracula", "Какой шумный. Вы Немейского льва тоже заговорили до смерти?",
			"So loud. Did you talk the Nemean lion to death as well?"]],
		[["dracula", "Сын Зевса. Ваша кровь, должно быть, божественна.",
			"Son of Zeus. Your blood must be divine."],
		["hercules", "Попробуй достань, кровопийца!",
			"Try and get some, bloodsucker!"]],
	],
	"dracula|ilya": [
		[["ilya", "Ты, что ли, кровопийца заморский? Ну держись: у нас на Руси кровь не раздают.",
			"So you're the overseas bloodsucker? Brace yourself: in Rus we don't give blood away."],
		["dracula", "Какой… колоритный ужин. Надеюсь, вы не слишком солёный.",
			"What a… colourful dinner. I do hope you're not too salty."]],
		[["ilya", "Тридцать лет и три года я на печи сидел. Встал — и сразу ты. Не повезло тебе.",
			"Thirty-three years I sat on the stove. First thing I see when I get up — you. Bad luck for you."],
		["dracula", "Тридцать три года? Я четыреста лет пролежал в гробу. Не впечатлён.",
			"Thirty-three years? I spent four hundred in a coffin. Not impressed."]],
		[["dracula", "Вы защищаете свою землю, богатырь. Я тоже защищал свою. Только моей больше нет.",
			"You defend your land, hero. I defended mine too. Only mine is gone."],
		["ilya", "Жаль тебя, княже. А всё одно — кровь людскую пить не дам.",
			"I pity you, prince. All the same — I won't let you drink people's blood."]],
	],
	"dracula|koschei": [
		[["koschei", "Ещё один бессмертный. Скучно тебе, граф?",
			"Another deathless one. Are you bored, Count?"],
		["dracula", "Скучно? Нет. Одиноко. Но вам ли не знать.",
			"Bored? No. Lonely. But you would know."]],
		[["dracula", "Кощей! Говорят, вы чахнете над златом. Какая безвкусица.",
			"Koschei! They say you waste away over gold. How tasteless."],
		["koschei", "А ты — над кровью. Тоже мне, гурман.",
			"And you over blood. Some gourmet."]],
	],
	"dracula|medusa": [
		[["dracula", "Мадам, ваш взгляд убийственно хорош.",
			"Madam, your gaze is killer."],
		["medusa", "Буквально. Смотри — и станешь украшением моего сада.",
			"Literally. Keep looking and you'll decorate my garden."]],
		[["medusa", "Вампир. Тебя тоже назвали чудовищем?",
			"A vampire. Did they call you a monster too?"],
		["dracula", "Тысячу раз. Со временем начинаешь носить это как плащ.",
			"A thousand times. In time you wear it like a cape."]],
	],
	"dracula|sunwukong": [
		[["sunwukong", "О, летучая мышь! Я тоже умею превращаться — смотри!",
			"Ooh, a bat! I can transform too — watch!"],
		["dracula", "Очаровательно. Как цирк, только с посохом.",
			"Charming. Like a circus, but with a staff."]],
		[["dracula", "Бессмертная обезьяна? Ваша кровь, должно быть, бодрит.",
			"An immortal monkey? Your blood must be invigorating."],
		["sunwukong", "Укуси, если догонишь! Ха!",
			"Bite me if you can catch me! Ha!"]],
	],
	"hercules|ilya": [
		[["hercules", "Говорят, ты самый сильный на Руси? А я — во всей Элладе!",
			"They say you're the strongest in Rus? I'm the strongest in all of Hellas!"],
		["ilya", "Так давай померяемся. Только чур — без дубины по темечку.",
			"Then let's see. Only no clubbing me on the crown, mind."]],
		[["ilya", "Так ты и есть Геракл? Конюшни, слыхал, чистил.",
			"So you're Hercules? Heard you cleaned some stables."],
		["hercules", "Двенадцать подвигов, борода! А ты чем похвастаешь?",
			"Twelve labours, beardy! What have you got to boast about?"]],
	],
	"hercules|koschei": [
		[["hercules", "Говорят, ты спрятал свою смерть. Трус! Я свою вину не прячу — я её отрабатываю.",
			"They say you hid your death. Coward! I don't hide my guilt — I work it off."],
		["koschei", "Двенадцать подвигов, и всё ещё не простил себя? Мы похожи больше, чем ты думаешь, силач.",
			"Twelve labours and you still haven't forgiven yourself? We're more alike than you think, strongman."]],
		[["koschei", "Опять подвиг, силач? Сколько ни бей — меня не убьёшь.",
			"Another labour, strongman? Hit me all you like — you can't kill me."],
		["hercules", "А я не за этим. Я хочу, чтобы ты хоть что-то почувствовал!",
			"That's not what I'm after. I want you to feel something!"]],
	],
	"hercules|medusa": [
		[["medusa", "Сын Зевса. Твой брат Персей принёс мою голову на щите.",
			"Son of Zeus. Your brother Perseus carried my head on a shield."],
		["hercules", "Он мне брат по отцу, а не по делам. Давай честно, Горгона.",
			"He's my brother by father, not by deeds. Let's fight fair, Gorgon."]],
		[["hercules", "Только не смотри на меня — окаменею посреди замаха!",
			"Just don't look at me — I'll turn to stone mid-swing!"],
		["medusa", "Не бойся. Руку опустить успеешь. Наверное.",
			"Don't worry. You'll have time to lower your arm. Probably."]],
	],
	"hercules|sunwukong": [
		[["sunwukong", "Говорят, ты небо на плечах держал? А я на небе погром устроил!",
			"They say you held up the sky? I trashed the place!"],
		["hercules", "Так вот почему его пришлось держать! Иди-ка сюда!",
			"So that's why it needed holding up! Come here!"]],
		[["hercules", "Мартышка с палкой! Это будет быстрый подвиг.",
			"A monkey with a stick! This'll be a quick labour."],
		["sunwukong", "Палка растёт! И мартышка — тоже! Ха!",
			"The stick grows! And so does the monkey! Ha!"]],
	],
	"ilya|koschei": [
		[["ilya", "Кощей! Опять девицу украл, костлявый?",
			"Koschei! Kidnapped another maiden, bony?"],
		["koschei", "Только шкатулку, богатырь. Девицы нынче в телефонах сидят.",
			"Only a jewel box, hero. Maidens these days sit in their phones."]],
		[["koschei", "Ты меня всё равно не убьёшь, Илюша. Смерть моя далеко.",
			"You still can't kill me, Ilyusha. My death is far away."],
		["ilya", "А мне не убить надо — мне побить. Это я и без иглы умею.",
			"I don't need to kill you — just beat you. I can do that without a needle."]],
	],
	"ilya|medusa": [
		[["medusa", "Не смотри мне в глаза, старик. Окаменеешь.",
			"Don't look me in the eye, old man. You'll turn to stone."],
		["ilya", "Я тридцать три года сиднем сидел — каменеть мне не впервой.",
			"I sat like a stone for thirty-three years — I'm used to it."]],
		[["ilya", "Ох, девка, причёска у тебя… шипит.",
			"Oh, lass, your hairdo… it hisses."],
		["medusa", "Ещё слово про причёску — и станешь садовой статуей.",
			"One more word about my hair and you'll be a garden statue."]],
	],
	"ilya|sunwukong": [
		[["sunwukong", "Эй, бородач! Спорим, я тебя за семьдесят два прыжка обскачу?",
			"Hey, beardy! Bet I can outjump you in seventy-two leaps?"],
		["ilya", "Прыгай-прыгай, обезьяна. Палица — она быстрее.",
			"Jump all you like, monkey. A mace is faster."]],
		[["ilya", "Ты кто ж такой? Скоморох?",
			"And who are you then? A jester?"],
		["sunwukong", "Великий Мудрец, равный Небу! Ну и скоморох немножко.",
			"The Great Sage Equal to Heaven! And a bit of a jester."]],
	],
	"koschei|medusa": [
		[["medusa", "Кощей. Ты тоже чудовище из сказки.",
			"Koschei. Another monster from a fairy tale."],
		["koschei", "Из сказки — да. Чудовище — спорно. Как и ты, змейка.",
			"From a tale — yes. A monster — debatable. Like you, little snake."]],
		[["koschei", "Окаменить меня хочешь? Я и так почти камень.",
			"Want to turn me to stone? I'm nearly stone already."],
		["medusa", "Значит, взгляд мой тебе не страшен. А когти?",
			"Then my gaze won't scare you. What about my claws?"]],
	],
	"koschei|sunwukong": [
		[["sunwukong", "Ещё один, кто обманул смерть! Дай пять, костлявый!",
			"Another one who cheated death! High five, bony!"],
		["koschei", "Обманул? Я её спрятал. И пожалел. Не повторяй, обезьяна.",
			"Cheated? I hid it. And regretted it. Don't repeat that, monkey."]],
		[["koschei", "Попрыгун. Ты хоть знаешь, сколько стоит бессмертие?",
			"Jumping jack. Do you even know what immortality costs?"],
		["sunwukong", "Нисколько! Я его стащил! Ха!",
			"Nothing! I swiped it! Ha!"]],
	],
	"medusa|sunwukong": [
		[["sunwukong", "Змеи на голове! А можно погладить?",
			"Snakes on your head! Can I pet them?"],
		["medusa", "Попробуй. Они кусаются. Я — тоже.",
			"Try it. They bite. So do I."]],
		[["medusa", "Не смотри мне в глаза, обезьяна.",
			"Don't look me in the eye, monkey."],
		["sunwukong", "А я зажмурюсь — и всё равно попаду! Ха!",
			"I'll shut my eyes and still hit you! Ha!"]],
	],
	"anubis|anubis": [
		[["anubis", "Двое на страже. Кто же тогда взвешивает?",
			"Two on guard. Then who is weighing?"],
		["anubis", "Весы подождут. Они терпеливы.",
			"The scales will wait. They are patient."]],
	],
	"athena|athena": [
		[["athena", "Две Афины. Значит, одна из нас ошиблась.",
			"Two Athenas. So one of us is mistaken."],
		["athena", "Мудрость — признать ошибку. Но сначала — бой.",
			"Wisdom is admitting a mistake. But first — the fight."]],
	],
	"dracula|dracula": [
		[["dracula", "Вас тоже не отражают зеркала? Какое совпадение.",
			"Mirrors don't show you either? What a coincidence."],
		["dracula", "Один из нас — подделка. И я в своём замке не потерплю дешёвых копий.",
			"One of us is a fake. And I tolerate no cheap copies in my castle."]],
		[["dracula", "Позвольте пригласить себя же на танец.",
			"Allow me to invite myself to a dance."],
		["dracula", "С удовольствием. Веду я.",
			"With pleasure. I lead."]],
	],
	"hercules|hercules": [
		[["hercules", "Самозванец! Ты присвоил мои подвиги!",
			"Impostor! You stole my labours!"],
		["hercules", "Все двенадцать? Тогда тринадцатым будешь ты!",
			"All twelve? Then you'll be the thirteenth!"]],
	],
	"ilya|ilya": [
		[["ilya", "Ты кто таков? Я — Илья Муромец!",
			"And who might you be? I am Ilya Muromets!"],
		["ilya", "Врёшь! Это я Илья Муромец. А ты, видать, Илья Подмосковец.",
			"Liar! I'm Ilya Muromets. You must be some Ilya from the suburbs."]],
		[["ilya", "Гляжу — и борода моя, и палица моя.",
			"I look — and it's my beard, and my mace."],
		["ilya", "Только кулак — мой. Проверим!",
			"But the fist is mine. Let's find out!"]],
	],
	"koschei|koschei": [
		[["koschei", "Два Кощея — две смерти в двух иглах?",
			"Two Koscheis — two deaths in two needles?"],
		["koschei", "Или одна на двоих. Проверим, чья игла тоньше.",
			"Or one for both. Let's see whose needle is thinner."]],
	],
	"medusa|medusa": [
		[["medusa", "Посмотри на меня.",
			"Look at me."],
		["medusa", "Смотрю. Не каменею. Странно, правда?",
			"I am. I'm not turning to stone. Strange, isn't it?"]],
	],
	"sunwukong|sunwukong": [
		[["sunwukong", "Эй, это же я — семьдесят третье превращение!",
			"Hey, that's me — transformation seventy-three!"],
		["sunwukong", "Нет, это я настоящий! Наверное…",
			"No, I'm the real one! Probably…"]],
	],
	"anubis|avatar": [
		[["avatar", "Тут никто не умирает. Тут просто листают.",
			"Nobody dies here. They just scroll."],
		["anubis", "Поэтому тут никто и не живёт.",
			"That is why nobody lives here either."]],
		[["avatar", "Сколько времени? А, неважно.",
			"What time is it? Eh, doesn't matter."],
		["anubis", "Важно. Время — единственное, что я взвешиваю точно.",
			"It matters. Time is the one thing I weigh precisely."]],
	],
	"anubis|scroller": [
		[["scroller", "Тут у меня никто не умирает, пёсик. Вечный контент.",
			"Nobody dies in here, doggy. Eternal content."],
		["anubis", "Вечный — значит, мёртвый. Весы ждут.",
			"Eternal means dead. The scales are waiting."]],
		[["scroller", "Пёсик, сделай грустные глазки, зрители любят собачек!",
			"Doggy, do the sad eyes, viewers love puppies!"],
		["anubis", "Я не пёсик. Я твой последний модератор.",
			"I am not a puppy. I am your final moderator."]],
	],
	"athena|avatar": [
		[["avatar", "Зачем читать, если есть краткий пересказ за минуту?",
			"Why read when there's a one-minute summary?"],
		["athena", "Пересказ даёт ответы. Книга учит задавать вопросы.",
			"A summary gives answers. A book teaches you to ask questions."]],
		[["avatar", "Мне не надо думать — лента сама подскажет.",
			"I don't need to think — the feed will tell me."],
		["athena", "Лента подскажет, что купить. Думать придётся тебе.",
			"The feed will tell you what to buy. Thinking is up to you."]],
	],
	"athena|scroller": [
		[["scroller", "Богиня мудрости! Лайкни мой стрим, а?",
			"Goddess of wisdom! Like my stream, yeah?"],
		["athena", "Мудрость — это знать, когда выключить.",
			"Wisdom is knowing when to switch it off."]],
		[["scroller", "Афина, улыбнись в камеру! Мудрость без улыбки не продаётся!",
			"Athena, smile for the camera! Wisdom doesn't sell without a smile!"],
		["athena", "Мудрость вообще не продаётся.",
			"Wisdom doesn't sell at all."]],
	],
	"avatar|dracula": [
		[["avatar", "Ты кто? А, вампир. Видел тебя в рилсе. Скучно.",
			"Who are you? Oh, the vampire. Saw you in a reel. Boring."],
		["dracula", "Я пятьсот лет не видел своего отражения. А ты смотришь в своё — и не узнаёшь себя.",
			"I haven't seen my reflection in five hundred years. You stare at yours — and don't recognise yourself."]],
		[["avatar", "Ещё пять минуточек… и ещё пять…",
			"Five more minutes… and five more…"],
		["dracula", "Я тоже так говорил. Пятьсот лет назад.",
			"I said that too. Five hundred years ago."]],
	],
	"avatar|hercules": [
		[["avatar", "Двенадцать подвигов? Я за вечер двенадцать уровней прошёл.",
			"Twelve labours? I beat twelve levels in one evening."],
		["hercules", "А я свои — двенадцать лет. Поэтому и помню каждый.",
			"Mine took twelve years. That's why I remember every one."]],
		[["avatar", "Лень. Можно я просто посмотрю, как ты дерёшься?",
			"Can't be bothered. Can I just watch you fight?"],
		["hercules", "Нет уж! Подвиг сам себя не совершит!",
			"No way! A labour won't do itself!"]],
	],
	"avatar|ilya": [
		[["avatar", "Отстань, дед. У меня видос не досмотрен.",
			"Leave me alone, old man. My video isn't finished."],
		["ilya", "Эх, Сашка… Я тридцать три года на печи сиднем сидел — знаю, каково это. Вставай!",
			"Oh, Sasha… I sat on a stove for thirty-three years — I know how it feels. Get up!"]],
		[["avatar", "Дед, ты из какой игры? Скин прикольный.",
			"Grandpa, what game are you from? Cool skin."],
		["ilya", "Я не из игры, Сашка. Я из книжки. Той, что у тебя на полке пылится.",
			"I'm not from a game, Sasha. I'm from a book. The one gathering dust on your shelf."]],
	],
	"avatar|koschei": [
		[["avatar", "Можно я тут навсегда останусь? Тут ничего не болит.",
			"Can I just stay here forever? Nothing hurts here."],
		["koschei", "Я тоже так думал. Тысячу лет назад. Не повторяй моей ошибки.",
			"I thought so too. A thousand years ago. Don't repeat my mistake."]],
		[["avatar", "Ничего не хочу. Просто листать.",
			"I don't want anything. Just to scroll."],
		["koschei", "Вот и я когда-то ничего не хотел. Смотри, чем кончилось.",
			"I didn't want anything once either. Look how that ended."]],
	],
	"avatar|medusa": [
		[["avatar", "Не смотри на меня. Я в телефоне.",
			"Don't look at me. I'm on my phone."],
		["medusa", "Вот так и каменеют, мальчик. Не от моего взгляда — от своего.",
			"That's how people turn to stone, boy. Not from my gaze — from their own."]],
		[["avatar", "Все смотрят в экран. Я тоже.",
			"Everyone stares at a screen. So do I."],
		["medusa", "Я знаю, каково быть статуей, мальчик. Оживай.",
			"I know what it's like to be a statue, boy. Come back to life."]],
	],
	"avatar|sunwukong": [
		[["avatar", "Семьдесят два превращения? У меня сто скинов.",
			"Seventy-two transformations? I've got a hundred skins."],
		["sunwukong", "Скин меняет одёжку, а я меняю себя! Давай, догоняй!",
			"A skin changes your clothes — I change myself! Come on, keep up!"]],
		[["avatar", "Скучно…",
			"Boring…"],
		["sunwukong", "Скучно?! Со мной?! Ну держись, сейчас будет весело!",
			"Boring?! With me?! Hold on, this is about to get fun!"]],
	],
	"dracula|scroller": [
		[["scroller", "Граф! Ты мой самый популярный персонаж. Подпишешь контракт навечно?",
			"Count! You're my most popular character. Sign a contract — forever?"],
		["dracula", "Я уже подписал один договор навечно. Больше не подписываю.",
			"I have already signed one contract for eternity. I sign no more."]],
		[["scroller", "Граф, рейтинг падает! Больше крови в кадре!",
			"Count, ratings are dropping! More blood on camera!"],
		["dracula", "Вы вульгарны, сударь. Этого я не прощаю.",
			"You are vulgar, sir. That I do not forgive."]],
	],
	"hercules|scroller": [
		[["scroller", "Тринадцатый подвиг — пройти меня! Донаты приветствуются.",
			"Labour thirteen — beat me! Donations welcome."],
		["hercules", "Я вычистил Авгиевы конюшни. Твою берлогу тоже вычищу.",
			"I cleaned the Augean stables. I'll clean out your den too."]],
		[["scroller", "Геракл, сними челлендж: двенадцать подвигов за двенадцать секунд!",
			"Hercules, do a challenge: twelve labours in twelve seconds!"],
		["hercules", "Двенадцать лет, болван. И ни секундой меньше.",
			"Twelve years, you fool. Not a second less."]],
	],
	"ilya|scroller": [
		[["scroller", "НОВЫЙ ИВЕНТ! Илья Муромец против… меня! Ставьте лайки, не переключайтесь!",
			"NEW EVENT! Ilya Muromets versus… me! Smash that like, don't switch!"],
		["ilya", "Так это ты нитки дёргаешь? Ну, сейчас я их посрываю.",
			"So you're the one pulling the strings? Well, I'll tear them off."]],
		[["scroller", "Илюша, у тебя ноль подписчиков. Ноль! Позорище.",
			"Ilyusha, you've got zero followers. Zero! Embarrassing."],
		["ilya", "Зато у меня Русь за спиной. А у тебя — коробки от пиццы.",
			"But I've got Rus behind me. You've got pizza boxes."]],
	],
	"koschei|scroller": [
		[["scroller", "Кощеюшка, мы с тобой похожи: оба бессмертные, оба никуда не выходим.",
			"Koschei, old pal, we're alike: both deathless, both never go outside."],
		["koschei", "Я хотя бы чахну над златом. А ты — над крошками от чипсов.",
			"At least I waste away over gold. You — over chip crumbs."]],
		[["scroller", "Кощей, продай мне иглу! Будет лучший стрим года!",
			"Koschei, sell me the needle! Stream of the year!"],
		["koschei", "Тебе? Ты же её в первый день потеряешь в крошках.",
			"To you? You'd lose it in the crumbs on day one."]],
	],
	"medusa|scroller": [
		[["scroller", "Медуза! На тебя смотрят миллионы! Ну скажи, приятно?",
			"Medusa! Millions are watching you! Feels good, right?"],
		["medusa", "Миллионы смотрят — никто не видит. Я знаю разницу.",
			"Millions watch — nobody sees. I know the difference."]],
		[["scroller", "Медуза, посмотри в камеру! Ну пожалуйста, для превьюшки!",
			"Medusa, look at the camera! Please, for the thumbnail!"],
		["medusa", "С удовольствием. Только камера окаменеет. И ты вместе с ней.",
			"Gladly. Only the camera will turn to stone. And you with it."]],
	],
	"scroller|sunwukong": [
		[["scroller", "Царь обезьян! Ты же любишь веселье — оставайся тут навсегда!",
			"Monkey King! You love fun — stay here forever!"],
		["sunwukong", "Я пятьсот лет просидел под горой. Хватит с меня клеток — даже весёлых.",
			"I spent five hundred years under a mountain. No more cages — not even fun ones."]],
		[["scroller", "Укун, у тебя миллион клипов! Ты мой любимый контент!",
			"Wukong, you've got a million clips! You're my favourite content!"],
		["sunwukong", "Контент?! Я Великий Мудрец, равный Небу! А ты — крошка на худи!",
			"Content?! I'm the Great Sage Equal to Heaven! You're a crumb on a hoodie!"]],
	],
}

## Если для пары нет своего диалога — каждый говорит одну из своих общих фраз: id → варианты [ru, en].
const GENERIC_INTRO := {
	"ilya": [
		["Ну, выходи, кто бы ты ни был. На Руси гостей встречают — палицей.",
			"Step forward, whoever you are. In Rus we greet guests — with a mace."],
		["Ну, помолясь — и в бой!",
			"Well, a quick prayer — and into battle!"],
		["Кто с палицей придёт — от палицы и ляжет. Шучу. Почти.",
			"Whoever comes with a mace shall fall by the mace. Kidding. Mostly."],
	],
	"dracula": [
		["Добрый вечер. Позвольте пригласить вас на ужин… в качестве ужина.",
			"Good evening. Allow me to invite you to dinner… as the dinner."],
		["Ночь ещё молода. Как и вы — пока.",
			"The night is young. As are you — for now."],
		["Не бойтесь. Я кусаюсь только в конце.",
			"Fear not. I only bite at the end."],
	],
	"hercules": [
		["Двенадцать подвигов совершил. Ты будешь тринадцатым — коротким.",
			"Twelve labours I have done. You'll be the thirteenth — a short one."],
		["Разомнёмся! Я сегодня ещё ни одного льва не задушил.",
			"Let's warm up! I haven't wrestled a single lion today."],
		["Не моргай, а то пропустишь подвиг.",
			"Don't blink, or you'll miss a labour."],
	],
	"koschei": [
		["Меня убить нельзя — смерть моя на конце иглы. А жаль. Иногда очень хочется.",
			"I cannot be killed — my death lies at a needle's tip. A pity. Sometimes I'd really like to be."],
		["Злато моё не трожь. Остальное — бери, коль сможешь.",
			"Hands off my gold. Take the rest, if you can."],
		["Бейте, бейте. Мне всё равно не больно. К сожалению.",
			"Go on, hit me. It won't hurt anyway. Sadly."],
	],
	"athena": [
		["Мудрость — знать, когда сражаться. Сейчас — время.",
			"Wisdom is knowing when to fight. Now is the time."],
		["Я уже знаю, как ты атакуешь. Ты — ещё нет.",
			"I already know how you'll attack. You don't yet."],
		["Стратегия выигрывает войны. Копьё — бои.",
			"Strategy wins wars. The spear wins fights."],
	],
	"medusa": [
		["Ещё один герой. Не смотри мне в глаза — или смотри. Мне уже всё равно.",
			"Another hero. Don't look into my eyes — or do. I no longer care."],
		["Смотри куда угодно. Только не мне в глаза.",
			"Look anywhere you like. Just not in my eyes."],
		["Ещё один храбрец. Сад у меня большой.",
			"Another brave one. My garden is big."],
	],
	"sunwukong": [
		["Великий Мудрец, равный Небу, приветствует тебя! И сразу прощается.",
			"The Great Sage Equal to Heaven greets you! And says goodbye right away."],
		["Догони меня! Ой, ты уже отстал.",
			"Catch me! Oops, you're already behind."],
		["Посох, расти! Сейчас будет смешно.",
			"Grow, staff! This is going to be funny."],
	],
	"anubis": [
		["Не бойся. Я взвешиваю сердца, а не вырываю их.",
			"Do not fear. I weigh hearts, I do not tear them out."],
		["Твоё время ещё не пришло. Но я проверю.",
			"Your time has not come yet. But I will check."],
		["Весы ждут. Начнём.",
			"The scales are waiting. Let us begin."],
	],
	"avatar": [
		["Подожди, щас досмотрю…",
			"Hang on, almost done watching…"],
		["Чё надо? Я занят.",
			"What do you want? I'm busy."],
		["Давай быстрее, у меня видос на паузе.",
			"Hurry up, my video's on pause."],
	],
	"scroller": [
		["НОВЫЙ ИВЕНТ! Не переключайтесь!",
			"NEW EVENT! Don't switch!"],
		["Ставьте лайки! Сейчас кого-то разнесут!",
			"Smash that like! Someone's about to get wrecked!"],
		["Ещё одну катку? Ну давай, давай…",
			"One more match? Come on, come on…"],
	],
}

## Победная фраза, если для пары нет своей: id → варианты [ru, en].
const GENERIC_WIN := {
	"ilya": [
		["Отдохни, полежи. А я пойду — ещё не всех чудищ перебил.",
			"Lie down, rest. I'm off — plenty of monsters left."],
		["Вот и ладно. Вставай, отряхнись — да не балуй больше.",
			"There we go. Get up, dust off — and behave yourself."],
		["Сила — она не в палице, а в правде. Но палица тоже помогает.",
			"Strength isn't in the mace, it's in the truth. But the mace helps."],
	],
	"dracula": [
		["Восхитительно. Повторим в полнолуние?",
			"Delightful. Shall we repeat it at the full moon?"],
		["Вы были… питательны.",
			"You were… nourishing."],
		["Не провожайте. Я сам найду выход — через окно.",
			"Don't see me out. I'll find my own way — through the window."],
	],
	"hercules": [
		["Тринадцатый подвиг. Только легче почему-то не стало.",
			"The thirteenth labour. Somehow it didn't get any lighter."],
		["Ещё один подвиг в копилку! Кто следующий?",
			"Another labour for the collection! Who's next?"],
		["Хороший бой! Я почти вспотел.",
			"Good fight! I almost broke a sweat."],
	],
	"koschei": [
		["Опять победил. Опять не умер. Опять ничего не почувствовал.",
			"Won again. Didn't die again. Felt nothing again."],
		["Победил. Ничего не почувствовал. Как всегда.",
			"Won. Felt nothing. As always."],
		["Злато в сохранности. А больше мне и не надо… кажется.",
			"The gold is safe. And I need nothing more… I think."],
	],
	"athena": [
		["Победа — не правота. Запомни это. И я запомню.",
			"Victory is not righteousness. Remember that. So will I."],
		["Всё по плану. Как обычно.",
			"All according to plan. As usual."],
		["Ты дрался храбро. Теперь подумай.",
			"You fought bravely. Now think."],
	],
	"medusa": [
		["Ещё одна статуя в саду. Красивая. Все они красивые.",
			"One more statue for the garden. Beautiful. They all are."],
		["Не бойся, я не смотрела. В этот раз.",
			"Don't worry, I didn't look. This time."],
		["Уходи. И расскажи всем, что Медуза — не чудовище.",
			"Go. And tell everyone Medusa is not a monster."],
	],
	"sunwukong": [
		["Ха! Даже не вспотел. Ну ладно, чуть-чуть.",
			"Ha! Didn't even break a sweat. Well, maybe a little."],
		["Хи-хи! Догонялки окончены!",
			"Hee-hee! Game of tag is over!"],
		["Великий Мудрец снова победил! Аплодисменты!",
			"The Great Sage wins again! Applause!"],
	],
	"anubis": [
		["Твоё сердце легче, чем ты думал. Иди с миром.",
			"Your heart is lighter than you thought. Go in peace."],
		["Сердце твоё в порядке. Тело — уже не очень.",
			"Your heart is fine. Your body, less so."],
		["Иди. Весы подождут.",
			"Go. The scales can wait."],
	],
	"avatar": [
		["Ещё одно видео — и спать. Честно.",
			"One more video and then bed. Honest."],
		["Ну всё, можно дальше листать.",
			"Done. Back to scrolling."],
		["Изи. Следующий.",
			"Easy. Next."],
	],
	"scroller": [
		["Ну вот. Ещё одну катку? Ещё одну… навсегда.",
			"There. One more match? One more… forever."],
		["Не переключайтесь! Дальше — ещё интереснее!",
			"Don't switch! It only gets better!"],
		["Лайк, подписка, колокольчик!",
			"Like, subscribe, ring the bell!"],
	],
}

## Победа: победитель → проигравший → варианты [ru, en].
const WIN := {
	"ilya": {
		"ilya": [
			["Двух Муромцев земля Русская не выдержит.",
				"The Russian land can't hold two of me."],
		],
		"dracula": [
			["Вот и вся заморская наука. Чесночку тебе на дорожку!",
				"So much for foreign learning. Have some garlic for the road!"],
			["Лежи, отдыхай. Гроб-то, небось, помягче был?",
				"Lie down, rest. Your coffin was comfier, I bet?"],
			["Ты, княже, воин справный был. Жаль, что не на той стороне.",
				"You were a fine warrior, prince. Pity you're on the wrong side."],
		],
		"avatar": [
			["Вставай, Сашка. Ты ж богатырь, а не лежебока.",
				"Up you get, Sasha. You're a bogatyr, not a couch potato."],
			["Ну вот, Сашка, и проснулся.",
				"There you go, Sasha, you've woken up."],
		],
		"scroller": [
			["Всё, кукольник. Нитки кончились.",
				"That's it, puppeteer. You're out of string."],
			["Нитки твои мне на портянки пойдут.",
				"Your strings'll do for my foot wraps."],
		],
	},
	"dracula": {
		"ilya": [
			["Крепкий старик. Кровь — как медовуха: с ног сшибает.",
				"A sturdy old man. Blood like mead — knocks you off your feet."],
			["Ваша борода — единственное, что оказало мне сопротивление.",
				"Your beard was the only thing that put up a fight."],
			["Берегите свою землю, богатырь. Я свою не уберёг.",
				"Guard your land, hero. I failed to guard mine."],
		],
		"dracula": [
			["Двум графам в одном замке тесно.",
				"One castle is too small for two counts."],
		],
		"avatar": [
			["Посмотри в зеркало, юноша. Видишь? Это ты. Не потеряй его.",
				"Look in the mirror, young man. See? That's you. Don't lose him."],
			["Видите? Мир за экраном — живой. Как и вы.",
				"You see? The world beyond the screen is alive. As are you."],
		],
		"scroller": [
			["Твоя публика разошлась, хозяин. Даже я знаю, когда уйти со сцены.",
				"Your audience has left, host. Even I know when to leave the stage."],
			["Занавес, сударь.",
				"Curtain, sir."],
		],
	},
	"hercules": {
		"koschei": [
			["Вставай, костлявый. Смерть свою найдёшь — приходи, вместе поищем покой.",
				"Get up, bony. When you find your death, come — we'll look for peace together."],
			["Кости — не камень. Ломаются.",
				"Bones aren't stone. They break."],
			["Вставай. Тебе ещё жить и жить — хочешь ты того или нет.",
				"Get up. You've got a lot of living left — like it or not."],
		],
		"avatar": [
			["Тринадцатый подвиг — вернуть мальчика домой. Беру.",
				"Labour thirteen: bring the boy home. I'll take it."],
			["Видишь — сил хватило! Значит, и на остальное хватит.",
				"See — you had the strength! So you'll have it for the rest."],
		],
		"scroller": [
			["Берлога вычищена. Окна открыть, крошки вымести.",
				"The den is clean. Open the windows, sweep the crumbs."],
			["Тринадцатый подвиг выполнен!",
				"Thirteenth labour complete!"],
		],
	},
	"koschei": {
		"hercules": [
			["Сильный… А вину свою так и не поднял. Тяжелее палицы, а?",
				"Strong… Yet you never lifted your guilt. Heavier than a club, eh?"],
			["Двенадцать подвигов — а проиграл старику.",
				"Twelve labours — and you lost to an old man."],
			["Бей ещё. Мне не больно. А тебе — больнее.",
				"Hit me again. It doesn't hurt me. It hurts you more."],
		],
		"avatar": [
			["Больно? Хорошо. Значит, живой.",
				"Does it hurt? Good. That means you're alive."],
			["Чувствуешь? Это и есть жизнь.",
				"Feel that? That's life."],
		],
		"scroller": [
			["Смерть моя в игле, а твоя — в розетке. Выдернул.",
				"My death is in a needle — yours is in a socket. Unplugged."],
			["Вот и ты, бессмертный, узнал, каково проигрывать.",
				"Now you know how losing feels, deathless one."],
		],
	},
	"athena": {
		"medusa": [
			["Ты права. Я виновата. Но я не могу позволить тебе мстить миру.",
				"You are right. I am to blame. But I cannot let you take revenge on the world."],
			["Прости меня. Я должна была сказать это раньше.",
				"Forgive me. I should have said it long ago."],
			["Ты сильнее, чем я думала. И правее.",
				"You are stronger than I thought. And more right."],
		],
		"avatar": [
			["Вопрос был не «что посмотреть», а «кем стать».",
				"The question was never 'what to watch', but 'who to become'."],
			["Думай сам, Саша. Это и есть свобода.",
				"Think for yourself, Sasha. That is freedom."],
		],
		"scroller": [
			["Выключено.",
				"Switched off."],
			["Твоё шоу окончено. Стратегически.",
				"Your show is over. Strategically."],
		],
	},
	"medusa": {
		"athena": [
			["Теперь ты знаешь, каково это — проиграть ни за что.",
				"Now you know what it's like to lose for nothing."],
			["Посмотри мне в глаза, богиня. Не каменеешь? Значит, слышишь меня.",
				"Look me in the eye, goddess. Not turning to stone? Then you hear me."],
			["Я не просила быть чудовищем. Это ты меня им сделала.",
				"I never asked to be a monster. You made me one."],
		],
		"avatar": [
			["Посмотри на меня. Видишь — не окаменел. Значит, ещё не поздно.",
				"Look at me. See — you didn't turn to stone. It's not too late."],
			["Ты смотришь на меня — и видишь меня. Это главное.",
				"You look at me — and see me. That's what matters."],
		],
		"scroller": [
			["Посмотри мне в глаза. А, у тебя нет глаз. Только экран.",
				"Look me in the eye. Ah, you have no eyes. Only a screen."],
			["Твой экран погас. А мой взгляд — нет.",
				"Your screen went dark. My gaze did not."],
		],
	},
	"sunwukong": {
		"anubis": [
			["Передай весам: Царь обезьян ещё погуляет!",
				"Tell your scales: the Monkey King isn't done playing!"],
			["Ха! Смерть меня не догнала! Опять!",
				"Ha! Death didn't catch me! Again!"],
			["Пёсик, принеси палочку! Ой, это мой посох.",
				"Fetch the stick, doggy! Oops, that's my staff."],
		],
		"avatar": [
			["Ха! Догнал! А теперь — бегом из этой клетки!",
				"Ha! Caught you! Now — run out of this cage!"],
			["Догнал сам себя! Самая трудная игра!",
				"Caught yourself! The hardest game there is!"],
		],
		"scroller": [
			["Ивент окончен! Награда — свобода!",
				"Event over! The reward is freedom!"],
			["Конец передачи!",
				"End of broadcast!"],
		],
	},
	"anubis": {
		"sunwukong": [
			["Твоё имя снова в книге. Не бойся — до твоей страницы ещё далеко.",
				"Your name is back in the book. Fear not — your page is still far off."],
			["Догнал. Как и всех — рано или поздно.",
				"Caught you. As I catch everyone — sooner or later."],
			["Твоя проделка окончена, Царь обезьян.",
				"Your prank is over, Monkey King."],
		],
		"avatar": [
			["Сердце бьётся. Значит, твоя страница ещё не дописана.",
				"Your heart is beating. Your page is not finished yet."],
			["Сердце лёгкое. Иди домой, мальчик.",
				"Your heart is light. Go home, boy."],
		],
		"scroller": [
			["На весах — пусто. Приговор: выключить.",
				"The scale holds nothing. Verdict: switch off."],
			["Время вышло. Весы закрыты.",
				"Time is up. The scales are closed."],
		],
	},
}

## Ответ проигравшего — пары-соперники, зеркальные бои и финал: проигравший → победитель → варианты [ru, en].
## Вариант выбирается тем же зерном, что и победная реплика, поэтому отвечает именно на неё:
## число вариантов совпадает с WIN[победитель][проигравший].
const LOSE := {
	"ilya": {
		"ilya": [
			["Ладно… Пусть земля держит. Я полежу.",
				"Fine… Let the land hold you. I'll just lie here."],
		],
		"dracula": [
			["Медовуха… Эх, сейчас бы ковшик. Только не с тобой, кровопийца.",
				"Mead… Could use a mug right now. Just not with you, bloodsucker."],
			["Борода ещё отрастёт. А вот ты ко мне ещё придёшь — увидишь.",
				"The beard will grow back. And you'll be back for more — you'll see."],
			["Сберегу, княже. И за тебя тоже.",
				"I will, prince. For you too."],
		],
	},
	"dracula": {
		"ilya": [
			["Чеснок? Как банально. Я ждал от вас большего, богатырь.",
				"Garlic? How banal. I expected more of you, hero."],
			["Гроб хотя бы не разговаривает. Идите уже.",
				"At least a coffin doesn't talk. Just go."],
			["На той стороне… Князь, у которого нет земли, стоит там, где ему оставили место.",
				"The wrong side… A prince without a land stands where he's left room to stand."],
		],
		"dracula": [
			["Ничего. У меня есть ещё четыреста лет на реванш.",
				"No matter. I have four hundred more years for a rematch."],
		],
	},
	"hercules": {
		"koschei": [
			["Тяжелее. Но я её хотя бы несу, а не прячу в яйце.",
				"Heavier. But at least I carry mine, not hide it in an egg."],
			["Тринадцатый ещё впереди, костлявый!",
				"The thirteenth is still ahead, bony!"],
			["…Может, ты и прав. Но я всё равно встану.",
				"…Maybe you're right. But I'll get up anyway."],
		],
	},
	"koschei": {
		"hercules": [
			["Покой… Ты так говоришь, будто он где-то есть.",
				"Peace… You say it as if it exists somewhere."],
			["Ломаются. А болеть — не болят. Жаль.",
				"They break. They just don't hurt. Pity."],
			["В том-то и беда, силач.",
				"That's exactly the problem, strongman."],
		],
	},
	"athena": {
		"medusa": [
			["Знаю. Теперь — знаю.",
				"I know. Now — I know."],
			["Слышу. Впервые.",
				"I hear you. For the first time."],
			["Я знаю. И не знаю, как это исправить.",
				"I know. And I don't know how to fix it."],
		],
	},
	"medusa": {
		"athena": [
			["«Виновата». Тысячи лет я ждала этого слова. Повтори.",
				"'To blame.' I waited thousands of years for that word. Say it again."],
			["Опоздала на тысячи лет, богиня. Но… спасибо.",
				"Thousands of years late, goddess. But… thank you."],
			["Наконец-то ты смотришь на меня, а не сквозь.",
				"At last you look at me, not through me."],
		],
	},
	"sunwukong": {
		"anubis": [
			["Далеко — это сколько? Я быстро бегаю!",
				"How far is far? I run fast!"],
			["Поздно! Очень поздно, договорились?",
				"Later! Much later, deal?"],
			["Одна окончена — сто других впереди!",
				"One's over — a hundred more to come!"],
		],
	},
	"anubis": {
		"sunwukong": [
			["Передам. Весы терпеливы. Я — тоже.",
				"I will. The scales are patient. So am I."],
			["Не сегодня. Я терпелив.",
				"Not today. I am patient."],
			["Смейся. Перо истины смеха не боится.",
				"Laugh. The feather of truth does not fear laughter."],
		],
	},
	"avatar": {
		"ilya": [
			["…Дед, а чем там у тебя с Соловьём-разбойником кончилось?",
				"…Grandpa, how did it end with the Nightingale Robber?"],
			["…Мне снился богатырь. Это был ты?",
				"…I dreamt of a hero. Was that you?"],
		],
		"dracula": [
			["…А в зеркале правда я?",
				"…Is that really me in the mirror?"],
			["…А можно ещё раз посмотреть на рассвет?",
				"…Can I watch the sunrise again?"],
		],
		"hercules": [
			["…А можно я сам свою комнату уберу?",
				"…Can I tidy my room myself?"],
			["…А можно я тоже буду подвиги совершать?",
				"…Can I do labours too?"],
		],
		"koschei": [
			["…Ай. Больно. Это… хорошо?",
				"…Ow. That hurts. Is that… good?"],
			["…Чувствую. Странно. Хорошо.",
				"…I feel it. Strange. Good."],
		],
		"athena": [
			["…А можно вопрос?",
				"…Can I ask a question?"],
			["…Я подумал. Хочу домой.",
				"…I thought about it. I want to go home."],
		],
		"medusa": [
			["…Не окаменел. Значит, можно смотреть по-настоящему.",
				"…I didn't turn to stone. So I can really look."],
			["…Ты не страшная. Ты грустная.",
				"…You're not scary. You're sad."],
		],
		"sunwukong": [
			["…Ладно. Кто последний до выхода — тот нуб!",
				"…Fine. Last one to the exit is a noob!"],
			["…А теперь во что поиграем?",
				"…What do we play now?"],
		],
		"anubis": [
			["…Значит, я ещё не дочитан.",
				"…So my story isn't finished yet."],
			["…Спасибо, что не взвешиваете меня сегодня.",
				"…Thanks for not weighing me today."],
		],
	},
	"scroller": {
		"ilya": [
			["Э-эй… кто выключил стрим?..",
				"He-ey… who turned off the stream?.."],
			["Отпишусь… от всех… отпишусь…",
				"Unsubscribing… from everyone… unsubscribing…"],
		],
		"dracula": [
			["Не уходите… щас самое интересное…",
				"Don't go… the best part is coming…"],
			["Стрим… завершён…",
				"Stream… ended…"],
		],
		"hercules": [
			["Мои подписчики… где мои подписчики?..",
				"My followers… where are my followers?.."],
			["Мой рейтинг… мой рейтинг…",
				"My rating… my rating…"],
		],
		"koschei": [
			["Розетка… моя розетка…",
				"My socket… my socket…"],
			["Перезагрузка… перезагру…",
				"Rebooting… reboo…"],
		],
		"athena": [
			["Звук… выключен…",
				"Sound… muted…"],
			["Зрители… вернитесь…",
				"Viewers… come back…"],
		],
		"medusa": [
			["Нет сигнала… нет… сигнала…",
				"No signal… no… signal…"],
			["Чёрный экран… почему чёрный экран…",
				"Black screen… why a black screen…"],
		],
		"sunwukong": [
			["Ивент… отменён…",
				"Event… cancelled…"],
			["Батарея… разряжена…",
				"Battery… depleted…"],
		],
		"anubis": [
			["Аккаунт… удалён…",
				"Account… deleted…"],
			["Сессия… истекла…",
				"Session… expired…"],
		],
	},
}


static func _pick(lines: Array, seed_value: int):
	return lines[absi(seed_value) % lines.size()]


## Диалог перед боем: массив [кто, текст] на текущем языке (бойцы a и b — в любом порядке).
static func intro(a: String, b: String, seed_value: int) -> Array:
	var ids := [a, b]
	ids.sort()
	var variants: Array = INTRO.get("%s|%s" % ids, [])
	if variants.is_empty():
		var out_g := []
		var n := 0
		for id in [a, b]:
			if GENERIC_INTRO.has(id):
				var line: Array = _pick(GENERIC_INTRO[id], seed_value + n * 7)
				out_g.append([id, line[0] if Loc.lang == "ru" else line[1]])
			n += 1
		return out_g
	var out := []
	for line in _pick(variants, seed_value):
		out.append([line[0], line[1] if Loc.lang == "ru" else line[2]])
	return out


## Победная реплика или "".
static func win(winner: String, loser: String, seed_value: int) -> String:
	var lines: Array = WIN.get(winner, {}).get(loser, [])
	if lines.is_empty():
		lines = GENERIC_WIN.get(winner, [])
	if lines.is_empty():
		return ""
	var q: Array = _pick(lines, seed_value)
	return q[0] if Loc.lang == "ru" else q[1]


## Ответ проигравшего на победную реплику или "".
static func lose(loser: String, winner: String, seed_value: int) -> String:
	var lines: Array = LOSE.get(loser, {}).get(winner, [])
	if lines.is_empty():
		return ""
	var q: Array = _pick(lines, seed_value)
	return q[0] if Loc.lang == "ru" else q[1]
